### ISSUE TITLE
A way to theme selected text

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#10]
Right now almost everything is themeable, however, I want to make it so that the color of the text i've typed in is different 

![image](https://user-images.githubusercontent.com/13646790/180908540-9b9a9377-029c-462f-bbcb-d600273de05c.png)

For example in the screenshot above, the text i've already typed (alacr) should be a different color in what i'm selecting than black to indicate what portion of the text is matching

**Comment by philj56** [comment]
Good idea, I think I'd stayed away from doing something like that because in rofi it bold/underlines the match, which can't really be done with the way I handle fonts:

![example](https://user-images.githubusercontent.com/13610623/180982164-72f6a416-9961-42c8-8b23-a7f6cad03312.png)

Changing the colour on the other hand should be pretty straightforward, so I'll give it a go.

**Comment by philj56** [comment]
Ok, I've added `--selection-match-color` in 655bde52896b4d6995d0c1b349a7f34d0bb221b1.

![highlight](https://user-images.githubusercontent.com/13610623/181897117-94db2f00-7fe2-4b4b-af45-cb0fa52e7cd1.png)

**Comment by Kommynct** [comment]
Perfect thank you so much!!
