### ISSUE TITLE
Add support for Alt key

### ISSUE THREAD

**Issue by DoctorKnowsBetter** [philj56/tofi#100]
**Please add support:**
Alt-j - prev
Alt-k - next

**In general, the ideal scheme for travel is as follows:**
Ctrl-n / Ctrl-h / Ctrl-j / Alt-n / Alt-h / Alt-j - prev
Crlt-p / Ctrl-l / Ctrl-k / Alt-p / Alt-l / Alt-k - next

The reason is simple, many people use different combinations in different ways.

**_Or the coolest way is to add support for adding "keybind" yourself_**

**Comment by DoctorKnowsBetter** [comment]
For the test I tried to change the code and it does not work, Alt does not intercept (I am not good in C, so do not be angry if something is wrong)
```
	} else if (sym == XKB_KEY_Up || sym == XKB_KEY_Left || sym == XKB_KEY_ISO_Left_Tab
			|| ((key == KEY_K || key == KEY_P)
				&& (xkb_state_mod_name_is_active(
					    tofi->xkb_state,
					    XKB_MOD_NAME_CTRL,
					    XKB_STATE_MODS_EFFECTIVE)
			            ||
                                    xkb_state_mod_name_is_active(
					    tofi->xkb_state,
					    XKB_MOD_NAME_ALT,
					    XKB_STATE_MODS_EFFECTIVE)
                           ))
	) {
		select_previous_result(tofi);

**Comment by philj56** [comment]
Alright, I've done most of this in 4b86d9f487712e24b2288502f21c033a8d6790ad and cda2fc734378c733f93249958975df55366e8543. I didn't add `Ctrl-h` & `Ctrl-l`, as those are pretty non-standard; the normal behaviour for `Ctrl-h` is backspace, whereas there is no standard behaviour for `Ctrl-l` (at least outside the terminal).

> For the test I tried to change the code and it does not work, Alt does not intercept

Yeah that's due to how I was checking for whether a character is printable first, I've fixed that and tidied the code up a little.

> Or the coolest way is to add support for adding "keybind" yourself

That's the next "feature" I need to look into, though I'm not sure if I'll find a way of implementing it I'm happy with - keybindings are quite hard to do in a nice way. I'll make an issue on it and do some investigating.

**Comment by DoctorKnowsBetter** [comment]
@philj56 Thank you for your comprehensive answer. I will take a look at the git branches you sent me.
