### ISSUE TITLE
new desktop entries not recogonized

### ISSUE THREAD

**Issue by xcpky** [philj56/tofi#108]
I am using the latest tofi by aur. Today I installed lvim and supertuxkart, they have their desktop entries in` /usr/share/applications`, however tofi-drun can't find them, I tried reboot and reinstall tofi, all failed. btw I installed flatpak today, and from `update-desktop-databse`, I can see `/home/ykpcx/.local/share/flatpak/exports/share/applications, /var/lib/flatpak/exports/share/applications` are added to database. I am not sure if this is related.

**Comment by jthvai** [comment]
Have you tried running `update-desktop-database` as root?

**Comment by xcpky** [comment]
thx solved

**Comment by philj56** [comment]
Thanks for sorting this @jthvai. Also worth mentioning that this might also just be caused by tofi's caching not being perfect (it's a hard problem to solve). If anyone else comes across this, you can force a re-gen of the tofi's desktop file cache by deleting `$XDG_CACHE_HOME/tofi-drun`, or `$XDG_CACHE_HOME/tofi-compgen` for the normal program cache.
