### ISSUE TITLE
Height not scaled properly?

### ISSUE THREAD

**Issue by dimkr** [philj56/tofi#25]
Debian bookworm's tofi 0.1.1-2, or aaccdaa.

```
anchor = top
width = 100%
height = 26
horizontal = true
font-size = 10
prompt-text = "$ "
font = monospace
outline-width = 0
border-width = 0
background-color = #000000
text-color = #ffffff
selection-color = #000000
selection-background = #ffffff
num-results = 10
min-input-width = 64
result-spacing = 10
padding-top = 4
padding-bottom = 4
padding-left = 4
padding-right = 4
```

Scale factor 1:

![1](https://user-images.githubusercontent.com/1471149/185200044-007ab558-a500-4292-b225-39e9499674c5.png)

Scale factor 2:

![2](https://user-images.githubusercontent.com/1471149/185200049-92024129-5e66-426d-b58a-6d120ff15f59.png)

**Comment by philj56** [comment]
That's working as intended - window size (and others) are specified in pixels, font size in points. Doubling the scale factor doubles the point->pixel ratio, so your fonts grow twice as big, but the window stays the same.

It might not be a bad idea to add a  `--scale-pixels` option or similar though, if you'd rather have that behaviour. The main reason I didn't do that by default is because on scale factor > 1 displays, you lose the ability to make odd-pixel-sized things (such as a single-pixel wide outline).

As a side note, I didn't realise someone was looking into packaging this for Debian. Cool!

**Comment by dimkr** [comment]
> if you'd rather have that behaviour.

Yes! I'll try to implement this.

(And thanks for tofi, I like it a lot!)

**Comment by philj56** [comment]
No problem, glad you're enjoying it! I'm fine to do this myself, but if you want to do it then by all means go ahead.

Just a note, it'd be better to have it the other way round; rather than `--scale-pixels`, have `--scale-font` (which defaults to true). That way it's only one variable that needs to change (rather than all of the pixel values). Also, I don't think `--scale-pixels` would ever make sense with percentage values.

**Comment by dimkr** [comment]
@philj56 How about changing the meaning of `font-size` from points to pixels, or adding `font-size-pixels`? That would make font size consistent with other options.

**Comment by philj56** [comment]
Yeah I'd thought about that too, maybe you're right in adding another option. It's all a trade-off:

- `scale-font=false` is clear in what it does, but a little clunky (and "unscaled points" isn't really a useful unit).
- I'm not a fan of changing `font-size` to pixels, as point is the common unit which nearly every application uses.
- `font-size-pixels` is unclear in order of precedence, but makes the most sense otherwise.

The ideal situation would probably be to allow units to be specified on most values, so you could do things like:
```ini
font-size = 24px  # Will not scale with scale factor
border-width = 1  # Ditto (defaults to px)
width = 100dp  # Will scale with scale factor
```
Actually, maybe that's not such a problem - I'd thought it might make things much messier code-wise, but writing it out I realise it should be pretty straightforward as long as not too many units are supported. I think we should just need:

- font-size: `px`, `dp`, `pt`
- other dimensions: `px`, `dp`
- `%` for the values that currently support it (doesn't really make sense for the others)

What do you think? I'm not sure about the name `dp`, but I don't think there exists a unit with the precise definition I want (1dp = 1 px × scale factor)

**Comment by dimkr** [comment]
I don't think `px` and `dp` are very useful. I think most people who use a scaling factor of > 1 would prefer a 2px border with a scale factor of 2 and `border-width = 1`, so tofi is visually consistent with other wlroots ecosystem applications, without having to write per-monitor configuration files with adjusted dimensions.

It's nice to be able to make tofi pixel-perfect in high DPI setups, but I bet only a small minority of users wants that, and a `scale = false` option that turns off all scaling can make such users happy.

I see two main problems:
1. The `font_size * scale` thing: the font size doesn't need to be scaled (because it's specified in pt), or, changed from pt to px with scaling.
2. Some dimensions specified in px are not scaled, like the border size, so the proportions are different depending on the scale factor.

I think all sizes (including the border size) need to be scaled and specified in px, except the font size.

**Comment by philj56** [comment]
Yeah, maybe you're right. I don't really use any other Wayland applications that I theme manually, but doing some checking I see that even Sway treats `px` as scaled pixels, rather than device pixels I guess I'll follow that.

Seeing as this is a change in the defaults, here's my plan:

- Add a `scale` option, which defaults to false.
- Make a release, with warnings that the default is going to change in the next release.
- In the release after that, make `scale = true` the default (all dimension values are scaled by the scale factor), and don't scale fonts anymore if `scale = false` (but keep them in points).

Sound good?

**Comment by dimkr** [comment]
After very basic testing, it looks like this patch works:

```
diff --git a/src/main.c b/src/main.c
index 6284cda..4962f76 100644
--- a/src/main.c
+++ b/src/main.c
@@ -998,8 +998,15 @@ int main(int argc, char *argv[])
 	 */
 	parse_args(&tofi, argc, argv);
 
-	/* Scale fonts to the correct size. */
-	tofi.window.entry.font_size *= tofi.window.scale;
+	/* Scale to the correct size. */
+	tofi.window.width = MIN(tofi.window.width * tofi.window.scale, (uint32_t)tofi.output_width);
+	tofi.window.height = MIN(tofi.window.height * tofi.window.scale, (uint32_t)tofi.output_height);
+	tofi.window.entry.padding_top *= tofi.window.scale;
+	tofi.window.entry.padding_left *= tofi.window.scale;
+	tofi.window.entry.padding_bottom *= tofi.window.scale;
+	tofi.window.entry.padding_right *= tofi.window.scale;
+	tofi.window.entry.outline_width *= tofi.window.scale;
+	tofi.window.entry.border_width *= tofi.window.scale;
 
 	/*
 	 * If we were invoked as tofi-run, generate the command list.
```

The text doesn't grow proportionally with scale factor 2, but everything else is scaled correctly.

**Comment by philj56** [comment]
Alright, I've made the change in ea64fc43a6a321fcc7417f35d5ce50a2c7ee9d7e. You should now be able to add `scale = true` and everything work as expected. I'll make a release soon with a warning that the default will change in the release after.

> it looks like this patch works

Thanks - there's a few more values around as well, I've made the changes in [config.c](https://github.com/philj56/tofi/blob/ea64fc43a6a321fcc7417f35d5ce50a2c7ee9d7e/src/config.c#L364). It'd be nice if I could just make it part of the `parse_uint32` / `parse_uint32_percent` functions, but there are some issues with the order things happen in, and this is good enough.

Thanks for bringing this up and discussing it with me!

**Comment by dimkr** [comment]
> Thanks for bringing this up and discussing it with me!

Thank you for your great work!
