### ISSUE TITLE
Prevent multiple instances to be opened

### ISSUE THREAD

**Issue by devgioele** [philj56/tofi#50]
I know this is not a crucial feature, but I mention it for the record.

When the user opens tofi multiple times by accident, multiple instances open. Because it is annoying to close multiple instances, it would be great to have at most one instance open at a time.

Proposal:
The current pid is written to `$XDG_RUNTIME_DIR/<app>.pid`. The existence and content of the file is checked on startup. Exit if the pid specified in the file does still exist.

**Comment by philj56** [comment]
Yeah, this is something I keep meaning to fix but forgetting about actually! I'll sort that soon.

**Comment by philj56** [comment]
Alright, this is done in 68587e2920b52ad75f0badb4d3040b574797ac9e with an option to control it in 0d779ef6359ff8a66b7c22ca7dee6b6097faa903. Turns out there's a somewhat neater way than using the pid (which would have been my default guess) - you can just try to place a lock on an empty file, and it's automatically released whenever the process exits. That way you don't have to worry about pid's being reassigned or do any file I/O, which is nice (though you do carry round an open file descriptor, which it's worth being aware of).
