### ISSUE TITLE
[QA] Ligatures Support

### ISSUE THREAD

**Issue by hikkidev** [philj56/tofi#64]
Is it realistic to add a font ligature rendering?

**Comment by philj56** [comment]
I'm not sure what you mean - it should already support ligatures, providing the font you're using does:

![ligatures](https://user-images.githubusercontent.com/13610623/202429947-9c6be451-596a-4611-b29a-d407f8f8783f.png)

**Comment by hikkidev** [comment]
![image](https://user-images.githubusercontent.com/52655010/202487102-01d65c32-9966-44d9-89f9-c6e1d038786e.png)

**Comment by hikkidev** [comment]
For example, prefix `run ->`. The arrow `->` should be  be something like this →
![image](https://user-images.githubusercontent.com/52655010/202487603-fb1c865a-7deb-47a8-843d-27c10cdc0a02.png)

**Comment by philj56** [comment]
This is mostly up to the font to support, rather than tofi. For example, Fira Code enables ligatures like this by default:

```sh
tofi-run --prompt-text "run ->" --font "Fira Code"
```
![ligature](https://user-images.githubusercontent.com/13610623/202492351-af15b2a5-b0f1-4741-88c2-2e4011c89c71.png)

Some fonts do have ligatures which aren't used by default though, and tofi doesn't explicitly enable these. I could look into allowing [OpenType features](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/OpenType_fonts_guide) to be specified at some point, but I don't know how complex it'll be.

**Comment by philj56** [comment]
Ok, I've added a `--font-features` option in 8fb1b007ebe93efb6bf6d928edfd235b086ed199. This lets you specify font features similar to CSS, so you can do things like

```sh
tofi-run --font-features "liga 0"  # Disable normal ligatures
tofi-run --font-features "dlig"  # Enable extra discretionary ligatures
tofi-run --font-features "c2sc, smcp"  # Convert all text to small caps
```

I've also added a `--font-variations` option in 8ff917954773b293276c2eda31959acbecdc2421, which lets you control variable fonts, e.g.

```sh
tofi-run --font-variations "wght 800"  # Extra bold text
```

Note that you may need a pretty new version of HarfBuzz installed for this to work though.
