### ISSUE TITLE
drun option

### ISSUE THREAD

**Issue by microo8** [philj56/tofi#7]
Is there a way to run it as `rofi -show drun` to see all installed applications (all .desktop files)?

**Comment by philj56** [comment]
Not in tofi itself, but you can use [j4-dmenu-desktop](https://github.com/enkore/j4-dmenu-desktop) to get that functionality with:
```
j4-dmenu-desktop --dmenu=tofi
```

**Comment by microo8** [comment]
Thanks. But are you considering to add such a feature to tofi?

**Comment by philj56** [comment]
I've had a look through the [Desktop Entry Spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.5.html), and it looks fairly complex for such a small program. Just as an example, `sloccount` currently puts tofi at 2992 lines of C, and j4-dmenu-desktop at 1023 lines of C++, so it'd likely be a significant increase in complexity.

I'm not 100% opposed to adding this functionality, but I don't have a need for it myself. I'll give it a quick go, in case it turns out to be significantly more straightforward than expected, but no promises.

In either case, I'll leave this issue open - if I don't do it soon and people really want this over using j4-dmenu-desktop, I'm open to being swayed by public opinion :)

**Comment by microo8** [comment]
I think I oversimplify it but:

1. these are the paths it searches for `.desktop` files: [SearchPath.generate](https://github.com/enkore/j4-dmenu-desktop/blob/7a64862ebb2304b1e08d3e00d622c5c76cc9b275/src/SearchPath.hh#L39)
2. and then this is a cryptic c++ thing doing parsing of the file: [Application.read](https://github.com/enkore/j4-dmenu-desktop/blob/7a64862ebb2304b1e08d3e00d622c5c76cc9b275/src/Application.hh#L74)

Some things in this new c++ are weird. But the parsing bit is mostly C. So maybe it could be ported. But I don't know if I want so start working on it on my own :/

**Comment by philj56** [comment]
Ok, so this turned out to be not quite as bad as I thought (~500 LOC, though that's not a great measure), and I've added it in 9e8af9d25106b615dabf956305f4ef80496ed412. It's a pretty basic implementation, but should mostly work. There's a brief example in the readme as well. Let me know if you find any issues!

As a side note:
> 1. these are the paths it searches for .desktop files: [SearchPath.generate](https://github.com/enkore/j4-dmenu-desktop/blob/7a64862ebb2304b1e08d3e00d622c5c76cc9b275/src/SearchPath.hh#L39)
> 1. and then this is a cryptic c++ thing doing parsing of the file: [Application.read](https://github.com/enkore/j4-dmenu-desktop/blob/7a64862ebb2304b1e08d3e00d622c5c76cc9b275/src/Application.hh#L74)

Thanks for the research, but I didn't (and won't) study j4-dmenu-desktop's code for this, as that's licensed under GPL and tofi's MIT.

**Comment by microo8** [comment]
This is great! I think it is much quicker, than using j4-dmenu-desktop.

> Thanks for the research, but I didn't (and won't) study j4-dmenu-desktop's code for this, as that's licensed under GPL and tofi's MIT.

I didn't check the licenses :/

Great job! Thanks again
