### ISSUE TITLE
tofi no longer displaying flatpaks in search

### ISSUE THREAD

**Issue by pottishb** [philj56/tofi#81]
Not really sure what changed but after a recent reboot I can no longer search for flatpak apps. Is there a setting I'm missing?

**Comment by philj56** [comment]
Nothing regarding how tofi finds programs has changed recently, so I'm not sure what would have broken. The way it works is:

For `tofi-run`:
- Check if a cache file exists at `$XDG_CACHE_HOME/tofi-compgen` (defaulting to `~/.cache`), and if it does and is up-to-date, load the list of programs from that.
- If the cache is out of date or non-existent, scan each folder in `$PATH` for executables

For `tofi-drun`:
- Same as before, look for a cache at `$XDG_CACHE_HOME/tofi-drun`.
- Otherwise, look through every folder in `$XDG_DATA_DIRS` (defaulting to `/usr/local/share:/usr/share`) for folders named `applications`, and scan those for `.desktop` files.

So depending on which of those has stopped working, it's presumably either a flatpak change that's done something weird, something's gone wrong with your environment variables, or tofi's caches have broken in some way and aren't being updated.

Deleting the two cache files or checking your environment variables may solve the issue, but otherwise I'm not sure.

**Comment by pottishb** [comment]
sweet, I knew I had forgotten something. Accidentally changed from drun to run. Thank you

**Comment by philj56** [comment]
Ah, I'm glad it was something simple!
