### ISSUE TITLE
Dont oppening programs in terminal

### ISSUE THREAD

**Issue by hoopengo** [philj56/tofi#87]
Hy, im using hyprland, and i tryed many things to open `htop`, but anyway it doesnt. Is it a bug?

**Comment by philj56** [comment]
Are you using `tofi-drun`? If so, you probably need to either set the `$TERMINAL` environment variable or pass the terminal name to tofi e.g. `tofi-drun --terminal foot`. There's some more discussion of this at #46 (and if you run `tofi-drun` from a terminal and select a terminal application such as `htop`, you'll get a warning message telling you what to do).

**Comment by hoopengo** [comment]
everything is fine, I just uninstalled tofi and installed rofi, it works fine

**Comment by philj56** [comment]
lol

**Comment by danilanosikov** [comment]
In case you would like to try out tofi again: the solution in my case was the following:
 
1. Comment out `drun-launch=true` inside of `.config/tofi/config`.
2. As already mentioned by philj56, set $TERMINAL veriabel to your terminal of choice, this is optional if you configured terminal inside tofi config file.
3. Instead of using `tofi-drun --drun-launch=true` for startup - use 'tofi-drun'
4. (In case you are using Hyprland) - In case some programs still wouldn't run - use: `tofi-drun | xargs hyprctl dispatch exec --`

Hope this would help, if you are stil considering on using tofi.

**Comment by machitgarha** [comment]
Is `--terminal` documented? I know `terminal` config is, but haven't seen the former.

**Comment by danilanosikov** [comment]
> Is `--terminal` documented? I know `terminal` config is, but haven't seen the former.

I haven't found any documentation for --terminal option yet, I would guess any option present in the config file in cli works the same as the original but with -- prefix, not sure though, since, again, no docs, which I saw, tell it explicidly.

I tried following:
`tofi-drun --terminal=foot | xargs hyprctl dispatch exec --`
and it worked normally, but I can't tell if it would work with several different
terminals, since I have only foot installed right now.
 
misspelled option spits an error, so I would guess it works the same as in config:
`tofi-drun --terrrrrminal=foot | xargs hyprctl dispatch exec --`

Hope it helps you, if it is still relevant to you.
