### ISSUE TITLE
No keyboard repeat rate

### ISSUE THREAD

**Issue by Kommynct** [philj56/tofi#9]
If you hold down up/down/any key there's no keyboard repeat

**Comment by philj56** [comment]
Yeah, that's something I've so far deliberately not done as it's a bit of a pain with how I've set up the rendering in tofi (basically, re-render every keypress). I'll probably get round to it at some point, but I don't have any need for it, so it may be a little while.

**Comment by philj56** [comment]
Ok, this should be working as of 02497d8e31876e6269f8686c44ec4f23a09cf5eb. It turned out not to be too bad, once I discovered the relevant [manpage](https://man.archlinux.org/man/wl_display.3#int_wl_display_prepare_read_queue_(struct_%3Cb%3Ewl_display%3C/b%3E_*_display,_struct_%3Cb%3Ewl_event_queue%3C/b%3E_*_queue)) that has a piece of example code using `poll()` (which you can supply a timeout to). I feel like core Wayland is generally missing examples for stuff like this, but that's by the bye.

**Comment by Kommynct** [comment]
AWESOME THANK YOU!

**Comment by jgbyrne** [comment]
Thanks for this!
